version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app/main.py
      - FLASK_ENV=production
    volumes:
      - tesla-leads-data:/app/data

volumes:
  tesla-leads-data: